Blank_state={
    "issue_id": None,  # generated by IssueIDGenerator
    "issue_type" : None,
    "image_paths": [],  # original image path
    "metadata": None,  # output of MetadataExtractor

    "status": "created",  # current stage in pipeline
    "admin_stage": "metadata_review",  # first approval needed,
    "stage":"stage_1",

    "approvals": {
        "metadata_review": False,
        "authority_review": False,
        "tweet_review": False,
    },

    "Authority_info": {
        "Name": None,
        "Email": None,
        "Department": None
    },

    "tweet": {
        "text": None,
        "status": "pending",
        "url": None
    },

    "email": {
        "status": "pending",
        "timestamp": None
    },

    "stored": False,
    "history": [],
    "errors" : {},
    "similar_to": None,
    "already_reported": None,
    "similar_count": 0,
    "similar_image_paths": []
}
